#!/usr/bin/env bash
#
# Visualize IMDB ratings of most recent top box office movies
#
# A one-liner that dislay the IMDB ratings of recent box office movies and visualize them using Spark
#
# holman's spark must be installed to show a nice ▄██▁▁▁▄█▄█ in the output.
# If you don't want the spark, just remove the '| spark' from end of the script.
#
# Sample output:

# Bad Grandpa             http://www.imdb.com/title/tt3063516/     7.1 
# Gravity                 http://www.imdb.com/title/tt1454468/     8.6 
# Captain Phillips        http://www.imdb.com/title/tt1535109/     8.1 
# The Counselor           http://www.imdb.com/title/tt2193215/     6.2 
# Carrie                  http://www.imdb.com/title/tt1939659/     6.4 
# Escape Plan             http://www.imdb.com/title/tt1211956/     7.3 
# 12 Years a Slave        http://www.imdb.com/title/tt2024544/     8.2 
# Enough Said             http://www.imdb.com/title/tt2390361/     7.5 
# Prisoners               http://www.imdb.com/title/tt1392214/     8.1 
# ▄██▁▁▁▄█▄█

curl --silent http://www.imdb.com/chart/ | grep "<a  href=" | \
while IFS= read -r l; do \
u=http://www.imdb.com$(echo $l | awk -F"[>\"<]" '{print $3}'); \
na=$(echo $l | awk -F"[>\"<]" '{print $5}'); \
curl --silent $u | grep "box-giga-star" | \
awk -v name="$na" -v ur="$u" -F"[><]" \
'{print $3};   {printf("%-20s\t%-20s\t%s\n", name,ur,$3) > "/dev/stderr"};'; \
done  | spark

